DEVICE: cuda:0
NUM_OF_GPU_TRAIN: 1
INITIAL_SEED: 42
TOOLBOX_MODE: 'train and test'

PREPROCESS:
  DO: True
  CHUNK_LENGTH: 160
  BACKEND : 'RF' #HC, RF, MT
  RANDOM_FRAME: False

DATA:
  TYPE: 'vital-video' #Data Type
  DATA_PATH: "your/path" #Data Path
  JSON_PATH: 'your/path/numpy_path_with_gt.json' #Data processing save path (including the JSON file name).
  FS: 30

ENSEMBLE:
  NUM: 3

RUN:
  DIR: "/run"

MODEL:
  PHYSFORMER:
    DROP_RATE: 0.1
    PATCH_SIZE: 4
    DIM: 96 
    FF_DIM: 144
    NUM_HEADS: 4
    NUM_LAYERS: 12
    THETA: 0.7

  PHYSNET:
    FRAME_NUM: 160

TRAIN: 
  BATCH_SIZE: 3
  EPOCHS: 30
  RESIZE:
    H: 128
    W: 128

TEST:
  USE_LAST_EPOCH: False


