DEVICE: cuda:0
NUM_OF_GPU_TRAIN: 1
INITIAL_SEED: 42
TOOLBOX_MODE: 'train and test'

ENSEMBLE:
  NUM: 3

RUN:
  DIR: "/run"

DATA:
  JSON_PATH: '/numpy_path_with_gt.json'
  FS: 30

PREPROCESS:
  CHUNK_LENGTH: 160

MODEL:
  PHYSFORMER:
    DROP_RATE: 0.1
    PATCH_SIZE: 4
    DIM: 96 
    FF_DIM: 144
    NUM_HEADS: 4
    NUM_LAYERS: 12
    THETA: 0.7

  PHYSNET:
    FRAME_NUM: 160

TRAIN: 
  BATCH_SIZE: 3
  EPOCHS: 30
  RESIZE:
    H: 128
    W: 128

TEST:
  USE_LAST_EPOCH: False


